curl -X POST -H "Content-Type: application/json" -d '{ "query": "MATCH (User) RETURN User.lang, count(User.lang) ORDER BY count(User.lang) DESC;" }' http://graph.calmisko.org/db/data/cypher > lang_count.json
curl -X POST -H "Content-Type: application/json" -d '{ "query": "MATCH (User)<-[:twitted_by]-(Twit)-[a:appears]->(Word) WHERE Word.is_tradermark = true AND User.lang = '"'"'cat'"'"' WITH Word, count(DISTINCT User) AS users RETURN Word, users ORDER BY users DESC LIMIT 25" }' http://graph.calmisko.org/db/data/cypher > lang_cat.json
curl -X POST -H "Content-Type: application/json" -d '{ "query": "MATCH (User)<-[:twitted_by]-(Twit)-[a:appears]->(Word) WHERE Word.is_tradermark = true AND User.lang = '"'"'en'"'"' WITH Word, count(DISTINCT User) AS users RETURN Word, users ORDER BY users DESC LIMIT 25" }' http://graph.calmisko.org/db/data/cypher > lang_en.json
curl -X POST -H "Content-Type: application/json" -d '{ "query": "MATCH (User)<-[:twitted_by]-(Twit)-[a:appears]->(Word) WHERE Word.is_tradermark = true AND User.lang = '"'"'es'"'"' WITH Word, count(DISTINCT User) AS users RETURN Word, users ORDER BY users DESC LIMIT 25" }' http://graph.calmisko.org/db/data/cypher  > lang_es.json
curl -X POST -H "Content-Type: application/json" -d '{ "query": "MATCH (Tweet)-[:appears]->(Word) WHERE Word.is_tradermark = true WITH Word, count(Tweet) AS tweets RETURN Word, tweets ORDER BY tweets DESC LIMIT 25" }'  http://graph.calmisko.org/db/data/cypher > query_1.json
curl -X POST -H "Content-Type: application/json" -d '{ "query": "MATCH (User)<-[:twitted_by]-(Twit)-[a:appears]->(Word) WHERE Word.is_tradermark = true WITH Word, count(DISTINCT User) AS users RETURN Word, users ORDER BY users DESC LIMIT 25" }'  http://graph.calmisko.org/db/data/cypher > query_2.json
curl -X POST -H "Content-Type: application/json" -d '{ "query": "MATCH (Tweet)-[:twitted_by]->(User) WITH User, count(Tweet) AS tweets RETURN User, tweets ORDER BY tweets DESC LIMIT 25" }'  http://graph.calmisko.org/db/data/cypher > query_3.json
curl -X POST -H "Content-Type: application/json" -d '{ "query": "MATCH (User)<-[:twitted_by]-(Tweet)-[a:appears]->(Word) WHERE Word.is_tradermark = true WITH User, count(Word) AS trademarks RETURN User, trademarks ORDER BY trademarks DESC LIMIT 25" }'  http://graph.calmisko.org/db/data/cypher > query_4.json
curl -X POST -H "Content-Type: application/json" -d '{ "query": "MATCH (Tweet)-[appears]->(Word) WHERE Word.is_tradermark = true WITH DISTINCT Tweet, Word MATCH (Word2)<-[appears]-(Tweet) WHERE Word2.is_tradermark = true and Word.value <> Word2.value WITH Word2.value as name, Word.value as name2, count(Word2) as size RETURN name, name2, size" }'  http://graph.calmisko.org/db/data/cypher > query_6.json
curl -X POST -H "Content-Type: application/json" -d '{ "query": "MATCH (Word)<-[:appears]-(Tweet)-[:appears]->(Word2) WHERE Word2.classification = '"'"'positive'"'"' AND Word.is_tradermark = true RETURN Word.value AS name, count(Tweet) AS size ORDER BY count(Tweet) DESC LIMIT 20" }'  http://graph.calmisko.org/db/data/cypher > query_7-1.json
curl -X POST -H "Content-Type: application/json" -d '{ "query": "MATCH (Word)<-[:appears]-(Tweet)-[:appears]->(Word2) WHERE Word2.classification = '"'"'negative'"'"' AND Word.is_tradermark = true RETURN Word.value AS name, count(Tweet) AS size ORDER BY count(Tweet) DESC LIMIT 20" }'  http://graph.calmisko.org/db/data/cypher > query_7-2.json
